ingress:
  host: keycloak.pf2e.io

image:
  tag: quay.io/keycloak/keycloak:18.0.0

port: 
  application: 8080
  service: 80

database:
  host: localhost
  port: 5432
  vendor: POSTGRES
  name: keycloak
  password: placeholder
  userId: placeholder