apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-credentials
  namespace: the-farmer
spec:
  encryptedData:
    password: AgATwROoSPcJDl+I4L8eygqB9UA5CmDA21PhyibiuTkybDtDVlnvQBMSSwVi36jM/5YtXe27WVisbYeEK2I1U6TrFOrGFH8tM6tYevxVGVYNu+O8DECEg7AaIuvBo6aysT22m2g0OYrnvPn/RC4lv8Cnq+5p5JGNTKobmzAeV56M42bvd6TAm3Yxiubf1/iB7ojCdRoVoA0+B0nJLcQemc017qSrvHAe3dAJqn/CNm83ng9/ZGtCu7aaQ0XM8fQRyZKASoF1sTfMfGt9ZKJhL0mol8evxcwTu9Hj1k/Q1+FjHN9PespDUxAVh9pLEPelFigvJEfKQAqFv8FkHk6mWYMTaiNUbRlUhaorTjUaFpFLO/UGcY5u6JQM64980uCvf55SrVcNIYltdaeqJ93iJHtwrSiS9DDP/GUu/irQgA4AXVo1kyzycI7y18AYmdbE92KylK4rhHODrHbM3XrXVLEdxF9HXd+2KZ4GixlzhwUOTgNZhUqhyUT+XO9kfHi5gmGYPoWuiGuUOxMR+LiGy936ICeaRzfQeQfmwAMBKXblWKMfktvXmlDl4MhhYn5tlnZNjoHXpa2UoSRbPF+lVWQJPYnudGHKf7cI9zNhUht7sqW4KauFA7nMTgJUxnzTAPzPIfsxURTt030wg54wrL3wO8Yi6wukAJqRGxWc75n/QFZBmE0NdNZTSnSXvkjZ5rSJYeq6mmfwk/alutTzfYtakThE
    username: AgAaQRTMDvh6Z5Ben8gMVrG3HT9TVahCNXj8LBt/vKwhpifOu308HSUAEIxeHvTF43zGFC6MNtVnqoHNEFf2ITybp7kkkZiUzKyOUWLqjuCKb1m9eLwxvVu6JyRxLoe6h934YDfc1LiHZVdOPDWTzSEqsmAtt76Pr7ck27dnExHGF49uzXG6Kgdo0MezwqvovEV5Bl3kZi/HZdDh81qqMP559MS7zL/isu7nk4dKrlWVy3tL7EH8yPBTTCtT1rkc/ScFmGfR/OMskp1mBrPSOt+9b2uRXOJn3OLzpHnjW7b7thg+w0GefZUTv2MPIkDtZ3BIrPcHjun6NTATf6XzyTfJZrpRtRYGxyzw65hn6NSCmOgyeOKf16FdxzR5KX0iN9nYma37q0mgSS1JJSBceCyzUdBADUC7srMkomrz6RRh/G8b1pM4CubaFs1DSPtTJnQ0CAJ6NtdLe2PkbRCylGoesptHE+pNxBO9eubGMaE6rSu4GUfgzp8P0pFnBxuN71sSU7C3uJPxz5Rjy3JrKbjCr75kG6qCQPXXUh3fOaiQAAeJ752LfGMhsAdDv5mQsVVkrn5GeFYkSQ7wUocKl3D8bbussEj9zDiBs0y4s1YDhplxX7YMnFiZtuAm9P/Eblawgs9Wt/x7/K2sDllVHCDbcMVdTBKqr0HIR9Xb2l1/e+KNRIWwZ5gJrdVGoKUH620FDHVQgBTaE/OjH4n+We6tQgEzxOd7MQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-credentials
      namespace: the-farmer

