apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-admin-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: AgB8dJHroEMNzWQKSUsASYSsLgFaScKvZvrYzyCO791vA6EzMy8sb/r6mqtOXBf/b5pPPFiwlZw6sX+ru6Ucaba/oiqBgRM3zxvwPHSCv8HPZTXlLOs93RbbU4112fT3dbTntp+7/YC76RlobI+d1wvBo/5udr7c5Jsyo9Hrcfa35jnOdJw38Lw+tcIpGbqarcBb12/yIknT+ptD8uyRViaHaw5LP0Byv3NdeN9gZk+ZnXKo5HgPP29/3l79ZUoxyoNvcxccUkB+V4voALnTkSkJg1qa5fJxIVx0ZIjInV3t1l1G9h0NAh7ZKqPrQxwxwtnywB/UBohwg3zZ5HSb9FM6ldSmgERvwnAP2hyv0w5KkLBRtnhnS5XTpzkCr5G1qBEEm0pwuBLinVwy5lCleVmPTwA3mSLgmdnlZvvF8nTTivSJP1RoW8iEmKsLh3AinspSHlD3Zaqv4I3c8Ot9YBxW0wiNWoKgztdsvIBRv+CgdBy+86+lJLxG3o3LHq0IMNEdq7IvnXBAJGMNkAJZ88Fiys4yNDMQBPeFGf3IJ1HUqc0ao9yIVmDAj97/LayW/IjKf/Sl6+4ZwcjLxiosLeCp9sbrjKRgK4KUG8cgc/fQYFAmLNfBUMMc1/0MLrUuUckHvRWXT+vGe3DJX1T98aggAyGI/9tZftSsHNpZmRpihmK55nQcSyEfjAHNuVflpOIfyZXj8A23uHIwHv4wR4E=
    username: AgANOxymSUVnnaT2n570jNQJZ43yKC5Hy1AJE4vTobPa4dsXn5kTbit5ifSwnBji4JFjzb96FQf8IPWNOvGLtgDzMWxGzCvr1brdjuSH9uTShiZraQbu5Jz2qIXl+ufzRC25qtpcfQQKEmcl1BtxsTCfhfMO5j+ecMcmiiYGc1cMuMBV6NCKkuixTGFTN/F345Y0cUECbhBrJvQQ+7fayB16mk5ov6jlA2nogpcu2cX6RuDDTfnBZVhig7B+WOiNN7Og5C9icxOQnG47CWQ66wGvOaI4XAqOHZTVRfyKPZW+Y2oyge1l03SfB2oEjy3AwzUvDPp5iO39LS2IqnhFY1ToAUF34DaSmcQSxo00vT2DGgn3+yHCbczrNeZdZqvqnODeWfG1iRVnwh4mPqvdcBMo536HxbdTuF9MJGGhKKXBQI0GJLCXEIZvR7QKx87yxGlySPMQygajXwmo8ohDI9jc/B7iWyKHdRQdJ9VmqcOnvwLeYjeLKTMh3Qa+esOsNBJ5B1Fj1K39GBbC2ADpB+x+mDEgMIEHzlQfSEBOKOwGs7DYKGPCQLtoD3eOc1pReUiGmT5YP3jXX3aA6Y186qUqAT/1krrm5z4r4m9YeMH24FLLxXzEW2AnmyyTVcVYhgy/U7zJvCZPVNqjqfb2VQ4oxJzD6yEHI64scqqc4idb1gE6nZmdmIbYMQTjXntU2LzpUu9Pq2ppejjwbLr06iApLS2GlnDvEg==
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-admin-credentials
      namespace: {{ .Release.Namespace }}

