apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: AgAl2qMHAfFsXKYiTH3kDa8gUFLJbtfZv3Z6QBALuXSWCJS+b6hEzvVT9m3MupDL+BNPEw15OZZUFWoxCpCDwbH2HUQy0VJWJSL1buQEI7469KqWkOrR8APrDvLt05YwOUnzH6fDZEOHz4UzmKLQjmdKCjnN7EJH4Ev1U8PbDVc0piKcUW2Hln8DxfHhxeDR2QFZa2EHIjci1p7QWbutFERheMqB5eAadRWwOfFI5VVilNAXzFXHQCI9DVnzfCflxNppGrW1b4DkOglpbmlrkobw03vmDWVwwhJWHO66pPEBB338qhUA4IJVZSkO3P9ePpo4c2vvXS/RPsWj47XZw4gm/5ChT6NCecPNOqZK40y9YzvajzWZCenb+OFKusiZ/0qxrHbHsdQp8Jry2zQ5sqy/EPvZ4+Iyw4O6wUUa0eD81SgOAcNCGIsOuWZd7i0BpcLAJuxlxz4p62fYteLm8zYJb5uu+GVYAoLaci+TYHJhZkkxbkUH8AVmcZSSLJbZnwf0MF8ptwKTeE5Uodr83Z0piZccwZZ15S7aJcPpWNqefBt2ysqHggKOnTAB6pqox+OL65AWJDkdIiAAbLrS2UG11xAr/Ml8uqjfWz6Ieh1xpO3KuV4V1Fxyq3ApebeOTYOVF/P8HRZjd37M6yjXpuUFNqUnxfeFprzubOKPXdvf2q008KZ23x+YtdBqcosvNbB4GwcxRD+M5H4gEc5VkOrNRFjHApAElTtpBia/Q9M=
    username: AgAEZmbav6Uw0BqaNbcjwi4HiVUII9JrPbzzTo+3ZjeMtx6VFI1I8ZQmec053opOGGfKdKQN6oBh8B6BjzvjxtUSR2WSmmlHY1tFGnZWt26l8mntfFSiclrYUIM4c75yEygpdaEBrLm3nfE6QdpaV+yoy/1Qld2fxnZh2pYNp7ZZ3V7H6cNoMqGBhdQIGg/BWWNpPgv2juTV7Q2IM7VkA0a6q552nporurVDLppXRHOqxL7RxZ8wTCz1bMIw/6gFohGUe/8BlsHtlmL7dSClxOMLAidT27SaOVzuTXcZhZGiKvAjItNl2h1DXkwO9RZuushXIhwwOrcN3lYSjVq7mjlPGma5dpaC8vruByGFeQvcMdDX/BXCflde1Oy1fGyUiQSpl+eFWylrQEAImkGqPSg1dG0rJQKfp0hqVS59qncGE2dSq8fcPJRnuAaxgMX4E1B3U4OqwJ4pWK0HgrmTtD+u1eEJ6Mj81LqDfXaiPGq0DfBGdML9OLVfWYNGP+ugfYoDV7KkWQ0lTpVHGPakPCb4CaZqAmEeF0yQfGLk0hiG3pYbIlOAcTFwkl7Ed3BVq8TZm7xpIVymv/jANTTZ0fKzZAyO24pIteq4sFujvXHn+BOzqRDMi/d1AHQkwNqHHUbUDjfTLpLUeyc4PmDvxEnOxXYKdXtv/lAf/VqYHmagbsYNQDwDZr6v7Wvr4JR90KIkKFipEnU=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-credentials
      namespace: the-farmer

