apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets.gcp-secret-store
    kind: SecretStore
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
  data:
  - secretKey: the-farmer_keycloak_username
    remoteRef:
      key: the-farmer_keycloak_username