apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
      - name: database-initialization
        image: busybox:1.28  
        command: ['sh']
        args:
        - '-c'
        - |
          echo "CREATE DATABASE {{ .Values.database.name }};" >> /docker-entrypoint-initdb.d/seed.sql
          echo "CREATE USER {{ .Values.database.userId }} WITH PASSWORD '{{ .Values.database.password }}';" >> /docker-entrypoint-initdb.d/seed.sql
          echo "GRANT ALL PRIVILEGES ON DATABASE {{ .Values.database.name }} TO {{ .Values.database.userId }};" >> /docker-entrypoint-initdb.d/seed.sql
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      containers:
      - name: {{ .Chart.Name }}-postgres
        image: postgres:13.2-alpine
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: 128Mi
            cpu: 0.1m
          limits:
            memory: 4096Mi
            cpu: 4
        env:
        - name: POSTGRES_DB
          value: {{.Values.database.name | quote}}
        - name: POSTGRES_PASSWORD
          value: {{.Values.database.password | quote}}
        - name: POSTGRES_USER
          value: {{.Values.database.userId | quote}}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", {{.Values.database.userId | quote}}]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", {{.Values.database.userId | quote}}]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        startupProbe:
          exec:
            command: ["pg_isready"]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 50
        volumeMounts:
        - name: clients
          mountPath: /var/lib/postgresql/data
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      - name: {{ .Release.Name }}
        image: {{ .Values.image.tag }}
        args: 
        - "start "
        - "--hostname "
        - "{{ .Values.ingress.host }}"
        env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: "DB_VENDOR"
          value: {{.Values.database.vendor }}
        - name: "DB_ADDR"
          value: {{.Values.database.host }}
        - name: "DB_PORT"
          value: {{.Values.database.port | quote}}
        - name: "DB_DATABASE"
          value: {{.Values.database.name }}
        - name: "DB_USER"
          value: {{.Values.database.userId }}
        - name: "DB_PASSWORD"
          value: {{.Values.database.password }}
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-admin-credentials
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-admin-credentials
              key: password
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: {{ .Values.port.application }}
        readinessProbe:
          httpGet:
            path: /realms/master
            port:  {{ .Values.port.application }}
      volumes:
        - name: clients
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clients-claim
        - name: initdb
          emptyDir: {}
          