apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: pathfinder
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "100"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslTermination | quote }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header x-forwarded-host {{ .Values.ingress.host | quote }};
      proxy_set_header x-forwarded-proto "https";
spec:
  rules:
  - host: {{ .Values.ingress.host  }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: {{{{ .Values.port.service }}
        path: /
  tls:
  - hosts:
    - {{ .Values.ingress.host  }}
    secretName: {{ .Chart.Name }}-tls

