apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-postgresql-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: the-farmer_keycloak_postgresql_username
  - secretKey: password
    remoteRef:
      key: the-farmer_keycloak_postgresql_password