apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql-credentials
  namespace: the-farmer
spec:
  encryptedData:
    password: AgBMUJZgEzTmEvuH+eHmZTrNERJ6AutGJQUH9mX0Sq6TUQ/LbbS1Vvno2arweoKkdpis5pK8ivoR1iJsk9Js/rV6J0bkWoC8RP1BIjmQBDwpVSXX4nRMEQhpWWxYFBs6BVyU3o2yYulmDSi9iHwcMIWVHHoC1cjmjV5MfuuCg2pu+yehAUcRkTC+jg9DCoK1MMjf1t57jj2U8MZin13A6hQaxLuiMts1cALQvERbHTFRJVojc0L72Zix5mnTwsZknWqrVr0O9ADegJJuUyuhj9w/mwlurNE1ZOE7a7cxGC5a7M/glzUbpS+7GTP6GaUm8GNmPFdJPQBkSQjNJyaLyZhIiy7ZqVCPb3OsKHgJhBdAzf0IruaQJpYTUD1+WgUDOOta3YFqo7ISpUFzXlvMQQYB400iczjRSy61oYZKQ0oFv9fyqq5wfwoEaJfa0JKW1ynujW4QRB5RGbmjs8LodWi16bMecJkiMyrfsjDfDHW4/bMX/uICqgYmAyeOWHlVPxFFSPthKojB1wU8gfbf400IU3xF4n6DOe1fSnC86eOoaLYpRUZj7A0UoV+bJJw2Ob6zldm1Uc3JzOgoNKVY4jmgkfEEBdPBqNCaeViIPCF6QlVUuL/83rHl7bpmRPOeeSP3r68XyELXjOBdQkiaHAa/iY5ThMbuGdCum9rqomtuow/+3szSKx6LPEKRUKkRGu0Uq7f1rJLtpbOHvLNMQQ1AvMF1dY6WQZ46E4AE9ckQPw==
    username: AgAVgbyhp4M9QRnYuf3rpbrstRUta/pnXzmTSHleNNwF69BDKzn9yKkNs+lL8moNuu6kC9/fRsht5kbtdon5vVn/yOfBXYLG/TxNTqKDI3x1iidC5RCB1j3tRA4XTQ9e2W47Am+iD0aGxfeFWIBul8Xc/08E785j/zCm0B9z1K7UYSxatvRfiOJFD5GDeCTtjRzSkioLbLVEjVX6dtLgZ0c2dimtgvTj3FKfY/fCoHB/nLH0vkb12hPecroWZyw8p8cGMxRKway4FiHsdaI5VYg5r1gJUf/tfm3ELMxgchhjKhFf9UdVoKsh53Hj5LulJB4loNmBpUhMhBtNedVA10VkmaGD170681SzW65CeZ0ReFc8qMviDxA4i4HD2x82S7xsaDk/CLFH6qGc7Wwjm2SR1urWNRKmStxpcWv7qpxzEUh3kaCX3+Q6S8Jzc+KHY0RE/yiJZR7AfCO1wROUwkJtP2wchsG4tZFEQcrBx+WDQtETpttBT0FRmren1PRCvDgXUiyFlbI1vBnjLPcmpUtbHXGTRGQ2VN7USe84WaOW7ZsXmYIs8ZbvA1WKrCxLlUc+HLpByVefriYt6vGY5SYgifBGkVNw/FAcyE3+ceZbkN50QxbPaBX7fMGaTJVNFhyW55HBb7CZjuNW6q8x66joPpwmG135VtPG7xTsewJCK5jRnFhm1kRAgDZdXMhIbwpo/bPPO8eabA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql-credentials
      namespace: the-farmer

